=== ese-omene/HTTP5203_Assignment2_EserogheneOmene/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="users">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="firstname">
                    <xs:complexType>
                      <xs:simpleContent>
                          <xs:extension base="xs:string">
                              <xs:attribute name="title" type="titles" use="optional"/>
                          </xs:extension>
                      </xs:simpleContent>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="lastname" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
              </xs:element>
              <xs:element name="username" type="xs:string" />
              <xs:element name="role" type="roles" />
              <xs:element name="id" type="validID" />
              <xs:element name="password" type="validPassword" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
<xs:simpleType name="roles">
  <xs:restriction base="xs:string">
    <xs:enumeration value="user" />
    <xs:enumeration value="support staff"/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="validID">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9]{6}" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="validPassword">
  <xs:restriction base="xs:string">
    <xs:pattern value="([A-Za-z]+[0-9]|[0-9]+[A-Za-z])[A-Za-z0-9]*" />
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name="titles">
  <xs:restriction base="xs:string">
    <xs:enumeration value="Mr." />
    <xs:enumeration value=" " />
    <xs:enumeration value="Mrs." />
    <xs:enumeration value="Ms." />
    <xs:enumeration value="Miss." />
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== ese-omene/HTTP5203_Assignment2_EserogheneOmene/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="users.xsd">
  <user>
    <name>
      <firstname title="Mr.">Bob</firstname>
      <lastname>Builder</lastname>
    </name>
    <username>BBuilder123</username>
    <role>user</role>
    <id>123456</id>
    <password>bal00n</password>
  </user>

  <user>
    <name>
      <firstname title="Ms.">Curly</firstname>
      <lastname>Sue</lastname>
    </name>
    <username>SuzyQ</username>
    <role>support staff</role>
    <id>123457</id>
    <password>m0nths</password>
  </user>

  <user>
    <name>
      <firstname>James</firstname>
      <lastname>Pop</lastname>
    </name>
    <username>JPop771</username>
    <role>user</role>
    <id>123458</id>
    <password>4ourth</password>
  </user>

</users>
